project_name: "Predictive_Maintenance_v1"
author: "Pranesh_Kannan_M_K"

data:
  raw_path: "data/raw/ai4i2020.csv"
  processed_dir: "data/processed/"
  production_dir: "data/production/"
  current_version: "v1"

model_params:
  algorithm: "RandomForest"
  n_estimators: 100
  max_depth: 10
  random_state: 42

deployment:
  model_path: "models/model_v1.pkl"
  port: 5050
  threshold: 0.75

monitoring:
  error_threshold: 0.15